name: Flutter_UI
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # - assets/images/photos
  # - assets/images/profileImages
  - assets/images/city.jpg
  - assets/images/profile1.jpg
  - assets/images/profile2.jpg
  - assets/images/grass.jpg
  - assets/images/background.jpeg
  - assets/images/photos/1.jpg
  -  assets/images/photos/2.jpeg
  - assets/images/photos/3.jpeg
  - assets/images/photos/4.jpeg
  - assets/images/photos/5.jpg
  - assets/images/photos/6.jpg
  - assets/images/photos/7.jpeg
  - assets/images/photos/8.jpeg
  - assets/images/photos/9.jpeg
  - assets/images/photos/10jpeg
  - assets/images/photos/11.jpeg
  - assets/images/photos/12.jpeg
  - assets/images/photos/13.jpeg
  - assets/images/photos/14.jpeg
  - assets/images/photos/15.jpeg
  - assets/images/photos/16.jpeg
  - assets/images/photos/17.jpg
  - assets/images/photos/18.jpg
  - assets/images/photos/19.jpg
  - assets/images/photos/20.jpg
  - assets/images/photos/21.jpg
  - assets/images/photos/22.jpg
  - assets/images/photos/23.jpg
  - assets/images/photos/profile1.jpg
  - assets/images/photos/profile2.jpg
  - assets/images/photos/profile3.jpg
  - assets/images/photos/profile4.jpg
  - assets/images/photos/profile5.jpg
  - assets/images/photos/profile6.jpeg
  - assets/images/photos/profile7.jpg
  - assets/images/photos/profile8.jpg
  - assets/images/photos/profile9.jpg
  - assets/images/photos/profile10.jpeg
  - assets/images/photos/profile11.jpg
  - assets/images/photos/profile12.jpg
  - assets/images/photos/profile13.jpeg
  - assets/images/photos/profile14.jpeg
  - assets/images/photos/profile15.jpeg
  - assets/images/photos/profile16.jpeg
  - assets/images/photos/profile17.jpg
  - assets/images/photos/profile18.jpg
  - assets/images/photos/profile19.jpeg
  - assets/images/photos/profile20.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
